version: '2.1'
services:
  agile-tool-db:
    image: microsoft/mssql-server-linux:2017-latest
    stdin_open: true
    tty: true
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=N0password
      - ACCEPT_EULA=y
    volumes:
      - /Users/jony/agile-tool/db:/db
