export const GET_USER_CLICK = 'PART3/GET_USER_CLICK';
export const GOT_USERS = 'PART3/GOT_USERS';
export const REFRESH_TOKEN_CLICK = 'PART3/REFRESH_TOKEN_CLICK';
export const REFRESHED_TOKEN = 'PART3/REFRESH_TOKEN_CLICK';
export const FETCH_TOKEN_ASYNC = 'PART3/FETCH_TOKEN_ASYNC';
